language: python
sudo: false
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  # Update conda itself
  - conda update --yes conda
install:
  # installing Qiita in it's own environment python2.7
  - travis_retry conda create --yes -n qiita python=2.7 pip nose flake8
    pyzmq networkx pyparsing natsort mock future libgfortran
    'pandas>=0.18' 'scipy>0.13.0' 'numpy>=1.7' 'h5py>=2.3.1'
  - source activate qiita
  - pip install sphinx sphinx-bootstrap-theme coveralls
  - pip install https://github.com/biocore/qiita/archive/master.zip --process-dependency-links
  # as we don't need redbiom we are going to use the default redis port
  - sed 's/PORT = 7777/PORT = 6379/g' $HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/config_test.cfg > config_test.cfg
  - export QIITA_CONFIG_FP=${PWD}/config_test.cfg
  - export QIITA_SERVER_CERT=$HOME/miniconda3/envs/qiita/lib/python2.7/site-packages/qiita_core/support_files/server.crt
  - qiita-env make --no-load-ontologies
  - source deactivate
  # installing this plugin
  - conda create --yes -n deblur-1.0.3 python=$PYTHON_VERSION numpy flake8
  - source activate deblur-1.0.3
  - conda install --yes -c bioconda -c biocore VSEARCH MAFFT=7.310 biom-format SortMeRNA==2.0 fragment-insertion
  - pip install https://github.com/biocore/deblur/archive/master.zip
  - pip install coveralls
  - pip install https://github.com/qiita-spots/qiita_client/archive/master.zip
  - pip install https://github.com/qiita-spots/qiita-files/archive/master.zip
  # for --process-dependency-links to work we need to have the latests version of pip
  - pip install -U pip
  - travis_retry pip install . --process-dependency-links
before_script:
  - source activate qiita
  - qiita pet webserver start &
script:
  - source activate deblur-1.0.3
  - sleep 10 # give enough time to the webserver to start
  - configure_deblur --env-script "source activate deblur-1.0.3" --server-cert $QIITA_SERVER_CERT
  - nosetests --with-doctest --with-coverage --cover-package=qp_deblur
  - flake8 qp_deblur setup.py scripts
addons:
  postgresql: "9.3"
services:
  - redis-server
  - postgresql
after_success:
  - coveralls
